apiVersion: v1
kind: Service
metadata:
  name: {{ include "casdoor.fullname" . }}
  labels:
    {{- include "casdoor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodePort }}
    {{- end }}
    {{- if .Values.ldap.enabled }}
    - name: ldap
      port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ldapNodePort }}
    {{- end }}
    {{- end }}
    {{- if .Values.ldaps.enabled }}
    - name: ldaps
      port: {{ .Values.service.ldapsPort }}
      targetPort: ldaps
      protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ldapsNodePort }}
    {{- end }}
    {{- end }}
    {{- if .Values.radius.enabled }}
    - name: radius
      port: {{ .Values.service.radiusPort }}
      targetPort: radius
      protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.radiusNodePort }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "casdoor.selectorLabels" . | nindent 4 }}
