#  Copyright 2025 ptrvsrg.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

version: 2
before:
  hooks:
    - sh -c 'mkdir -p manifests && touch manifests/crds_{{ .Version }}.yaml && cat config/crd/bases/*.yaml | awk "{print}" > manifests/crds_{{ .Version }}.yaml'
    - sh -c 'mkdir -p manifests && touch manifests/install_operator_{{ .Version }}.yaml && helm template ./charts/casdoor-operator --values ./charts/casdoor-operator/values.yaml --name-template test > manifests/install_operator_{{ .Version }}.yaml'
    - yarn --cwd docs --frozen-lockfile
    - yarn --cwd docs build
    - make crd
    - make boilerplate
    - go generate ./...
    - go mod download
builds:
  - id: operator
    builder: go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    main: cmd/main.go
    flags:
      - -mod=readonly
    ldflags:
      - -s
      - -w
      - -X github.com/ptrvsrg/casdoor-operator/internal/version.AppVersion={{ .Version }}
      - -X github.com/ptrvsrg/casdoor-operator/internal/version.GoVersion={{ .Env.GO_VERSION }}
      - -X github.com/ptrvsrg/casdoor-operator/internal/version.Platform={{ .Os }}/{{ .Arch }}
archives:
  - id: operator
    ids:
      - operator
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_{{- title .Os }}-{{ .Arch }}{{ if .Arm }}-{{ .Arm }}{{ end }}{{ if .Arm64 }}-{{ .Arm64 }}{{ end }}{{ if .Riscv64 }}-{{ .Riscv64 }}{{ end }}{{ if .Amd64 }}-{{ .Amd64 }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}{{ if .I386 }}-{{ .I386 }}{{ end }}{{ if .Ppc64 }}-{{ .Ppc64 }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    allow_different_binary_count: true
    files:
      - src: README.md
        dst: README.md
      - src: LICENSE.md
        dst: LICENSE.md
source:
  enabled: true
  format: zip
  name_template: >-
    {{ .ProjectName }}-docs_{{ .Tag }}
  files:
    - src: docs/build/*
      dst: static
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
release:
  github:
    owner: ptrvsrg
    name: casdoor-operator
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: manifests/crds_{{ .Version }}.yaml
      name_template: crds_{{ .Version }}.yaml
    - glob: manifests/install_operator_{{ .Version }}.yaml
      name_template: install_operator_{{ .Version }}.yaml
  header: |
    ## Release version {{ .Tag }} dated {{ .Date }}
    
    Welcome to new release of Casdoor Operator!
  footer: |
    This release is automatically generated by [goreleaser](https://github.com/goreleaser/goreleaser)