---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - casdoor.ptrvsrg.github.com
  resources:
  - casdoors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - casdoor.ptrvsrg.github.com
  resources:
  - casdoors/finalizers
  verbs:
  - update
- apiGroups:
  - casdoor.ptrvsrg.github.com
  resources:
  - casdoors/status
  verbs:
  - get
  - patch
  - update
