apiVersion: v1
entries:
  casdoor:
  - apiVersion: v2
    appVersion: v1.919.0
    created: "2025-05-25T10:25:22.935954635Z"
    description: A Helm chart for Casdoor
    digest: 94203dc977a025b1ecd35f42389a655dadd0709f0661b2e9b2292617b35a1e21
    icon: https://avatars.githubusercontent.com/u/72992104?s=200&v=4
    keywords:
    - casdoor
    - sso
    - auth
    maintainers:
    - name: ptrvsrg
    name: casdoor
    sources:
    - https://github.com/ptrvsrg/casdoor-operator
    type: application
    urls:
    - https://ptrvsrg.github.io/casdoor-operator/charts/casdoor-0.0.1.tgz
    version: 0.0.1
  casdoor-operator:
  - apiVersion: v2
    appVersion: refs/tags/v0.0.0-RC3
    created: "2025-05-25T10:25:22.936541676Z"
    description: A Helm chart for Kubernetes Operator for Casdoor
    digest: 2f0d2e6bdcbafd42b7d190903939e02a22e365a78daa52fc8adbad0b1ee14929
    icon: https://raw.githubusercontent.com/ptrvsrg/casdoor-operator/refs/heads/feature/1-init/.assets/logo.png
    keywords:
    - casdoor
    - operator
    - sso
    - auth
    maintainers:
    - name: ptrvsrg
    name: casdoor-operator
    sources:
    - https://github.com/ptrvsrg/casdoor-operator
    type: application
    urls:
    - https://ptrvsrg.github.io/casdoor-operator/charts/casdoor-operator-0.0.1.tgz
    version: 0.0.1
generated: "2025-05-25T10:25:22.934986956Z"
