import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'getting-started',
                }
            ],
        },
        {
            type: 'category',
            label: 'Deployment',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'deploy',
                }
            ],
        },
        {
            type: 'category',
            label: 'API Reference',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'api-reference',
                }
            ],
        },
    ],
};

export default sidebars;
