name: Documentation
on:
  push:
    branches:
      - '*'
    paths:
      - 'docs/**'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-RC[0-9]+"
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=18.0"
          cache: yarn
          node-version-file: docs/package.json
          cache-dependency-path: docs/yarn.lock
      - name: Dependency
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Build
        working-directory: docs
        run: yarn build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: docs/build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=18.0"
          cache: yarn
          node-version-file: docs/package.json
          cache-dependency-path: docs/yarn.lock
      - name: Test
        working-directory: docs
        run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || (github.event == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          destination_dir: .
          keep_files: true
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          commit_message: "Deploy documentation to GitHub Pages"
