name: Helm Chart
on:
  push:
    branches:
      - '*'
    paths:
      - 'charts/**'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-RC[0-9]+"
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Lint
        working-directory: charts
        run: ct lint --chart-dirs=. --all
  package:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - name: Package charts
        working-directory: charts
        run: ls -d */ | xargs -I$ sh -c 'helm package $ -d build --app-version ${{  github.ref }}' && helm repo index build --url https://ptrvsrg.github.io/casdoor-operator/charts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: charts/build
  deploy:
    needs:
      - package
    if:  github.ref_type == 'tag' || (github.event == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: charts/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./charts/build
          publish_branch: gh-pages
          destination_dir: ./charts
          keep_files: true
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          commit_message: "Deploy Helm Charts to GitHub Pages"